version: '3.4'

services:
  react_nginx:
    image: matorz/basic-react:build-latest
    ports:
      - 8888:80
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.hostname == devops2

